import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";
import {AuthProvider} from "@/app/contexts/AuthContext";
import React from "react";
import {ThemeProvider} from "@/app/contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
    return (

            <html lang="en">
                    <body>
                    <AuthProvider>
                        <ThemeProvider>
                            <div className="px-40 font-sans leading-normal min-h-screen">
                                <Header/>
                                {children}
                            </div>
                        </ThemeProvider>
                    </AuthProvider>
                    </body>


            </html>

    );
};

export default RootLayout;
